version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: 'db'
    ports:
      - "3306:3306"

networks:
  default:
    name: paymart
    external: true

